spring:
  r2dbc:
    #    url: r2dbc:oracle:thin://localhost:1521:XE
    #    username: system
    #    password: oracle
    url: r2dbc:h2:file:///./data/h2db/testdb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true
